version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=netalerte_cm
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - netalerte-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=netalerte_cm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - netalerte-network

  dashboard:
    build: ./dashboard
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - netalerte-network

volumes:
  postgres_data:

networks:
  netalerte-network:
    driver: bridge 